language: rust
sudo: false
cache: cargo

rust:
  - stable
  #- beta
  - nightly

services:
  - docker

before_install:
  - pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH

script:
  - |
      travis-cargo build &&
      ./tests/run-all-tests $KAFKA_VER &&
      travis-cargo bench &&
      travis-cargo --only stable doc

env:
  global:
    - RUST_TEST_THREADS: 1
    - TRAVIS_CARGO_NIGHTLY_FEATURE: nightly

  matrix:
    - KAFKA_VER=0.8.2.2 COMPRESSIONS=NONE
    - KAFKA_VER=0.8.2.2 COMPRESSIONS=SNAPPY
    - KAFKA_VER=0.8.2.2 COMPRESSIONS=GZIP
    - KAFKA_VER=0.9.0.1 COMPRESSIONS=NONE
    - KAFKA_VER=0.9.0.1 COMPRESSIONS=SNAPPY
    - KAFKA_VER=0.9.0.1 COMPRESSIONS=GZIP
    - KAFKA_VER=0.10.2.1 COMPRESSIONS=NONE
    - KAFKA_VER=0.10.2.1 COMPRESSIONS=SNAPPY
    - KAFKA_VER=0.10.2.1 COMPRESSIONS=GZIP
    - KAFKA_VER=latest COMPRESSIONS=NONE
    - KAFKA_VER=latest COMPRESSIONS=SNAPPY
    - KAFKA_VER=latest COMPRESSIONS=GZIP
