[package]
name = "kafka"
version = "0.1.0"
authors = ["Yousuf Fauzan https://github.com/spicavigo"]
description = "Rust client for Apache Kafka"
homepage = "https://github.com/spicavigo/kafka-rust"
repository = "https://github.com/spicavigo/kafka-rust"
readme = "README.md"
keywords = ["kafka", "apache"]
license = "MIT"


[dependencies]
num = "0.1"
byteorder = "0.3"
libc="0.1"
