[package]
name = "kafka"
version = "0.1.5"
authors = ["Yousuf Fauzan https://github.com/spicavigo"]
description = "Rust client for Apache Kafka"
homepage = "https://github.com/spicavigo/kafka-rust"
repository = "https://github.com/spicavigo/kafka-rust"
documentation = "http://fauzism.co/rustdoc/kafka/index.html"
readme = "README.md"
keywords = ["kafka", "apache"]
license = "MIT"


[dependencies]
num = "0.1"
byteorder = "0.3"
libc="0.1"
flate2 = "0.2"
